version: 2
jobs:
  build:
    working_directory: ~/bcredi-register
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: eslint
          command: npm run eslint
      - run:
          name: stylelint
          command: npm run stylelint
      - run:
          name: test
          command: npm test