defaults: &defaults
  docker:
      - image: circleci/node:10-browsers

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm run build
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: npm run test
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: npm run eslint
      - run: npm run stylelint

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - tests:
          requires:
            - lint
      - build:
          requires:
            - tests